import { ReactNode } from 'react';
import type { Metadata } from 'next';

import Sider from '@/components/Sider';

import './global.scss';
import styles from './page.module.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <body>
        <div className={styles.main}>
          <Sider />
          {children}
        </div>
      </body>
    </html>
  );
}
